GET http://localhost:3001/api/users

###

get http://localhost:3001/api/users/668d24412811c2cccbf35fb1

###

POST http://localhost:3001/api/users
Content-Type: application/json

  {
    "name": "Peter",
    "username": "Peter",
    "password": "Peter",
    "online": false,
    "email": "miriampilar999@gmail.com",
    "image": "../images/Hombre.jpg"
  }

###

DELETE http://localhost:3001/api/users/668d4d87098c1e8b29690aeb

