GET http://localhost:3001/api/films

###

POST http://localhost:3001/api/films
Content-Type: application/json

{
    "titulo": "La vie in rose",
    "vista": false,
    "buena": 1,
    "mala": 0,
    "idExterna": "43078"
}

###

DELETE http://localhost:3001/api/films/668d360aa34105aa94b37067


###

GET http://localhost:3001/api/films/668d360aa34105aa94b37067
