GET http://localhost:3001/api/films

###

POST http://localhost:3001/api/films
Content-Type: application/json

{
    "id": "10",
    "vista": false,
    "titulo": "Chalot",
    "buena": 1,
    "mala": 0
}

###

DELETE http://localhost:3001/api/films/10